# Generated by Django 2.2.5 on 2020-02-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
    ]
