# Generated by Django 3.0.3 on 2020-04-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200405_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='defo.png', upload_to='user_icon/'),
        ),
    ]
