# Generated by Django 3.0.3 on 2020-04-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200415_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_leaders',
            field=models.BooleanField(default=False, help_text='アカウントの追加処理などへのアクセス', verbose_name='leaders status'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
