version: "3"
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - staticfiles:/static
      - ./log/gunicorn:/app/log/gunicorn
    command: >
      /bin/bash -c "
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn -c gunicorn.py digigru.wsgi"
    environment:
      TZ: Asia/Tokyo
    restart: always
  web:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./log/nginx:/var/log/nginx
      - staticfiles:/static:ro
    depends_on:
      - app
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
    restart: always

volumes:
  staticfiles:
