version: "3"
services:
  app:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - staticfiles:/static
      - ./media:/app/media
      - ./log/gunicorn:/app/log/gunicorn
    command: >
      /bin/bash -c "
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn -c gunicorn.py digigru.wsgi"
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .conf/docker.env
    restart: always
  blog_next:
    build: blog-next
    ports:
      - 3000:3000
    restart: always
  core_next:
    build: core-next
    restart: always
    networks:
      - internal_network
      - https_network
  web:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./log/nginx:/var/log/nginx
      - staticfiles:/static:ro
      - ./media:/appmedia:ro
    ports:
      - 80:80
    depends_on:
      - app
    environment:
      TZ: Asia/Tokyo
    restart: always
  db:
    image: mariadb:10.4
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .conf/docker.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always

volumes:
  staticfiles:
