version: "3"
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - staticfiles:/static
      - ./media:/app/media
      - ./log/gunicorn:/app/log/gunicorn
    command: >
      /bin/bash -c "
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn -c gunicorn.py digigru.wsgi"
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .conf/docker.env
    restart: always
  web:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./log/nginx:/var/log/nginx
      - staticfiles:/static:ro
      - ./media:/appmedia:ro
    depends_on:
      - app
    environment:
      TZ: Asia/Tokyo
    restart: always
  https-portal:
    image: steveltn/https-portal:1
    volumes:
      - ./ssl_certs:/var/lib/https-portal
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAINS: "core.digicre.net -> http://web:80"
      STAGE: "production"
    restart: always
  db:
    image: mariadb:10.4
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .conf/docker.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always

volumes:
  staticfiles:
