# Generated by Django 3.0.3 on 2020-08-13 09:14

from django.conf import settings
from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'issue/fixture/init.json', app_label='issue')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('color', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('color', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('order', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('color', models.CharField(default='', max_length=20)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='表題')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.Category', verbose_name='種別')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issue.Priority', verbose_name='重要度')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.Status', verbose_name='ステータス')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),

        migrations.RunPython(load_fixture),
    ]
