# Generated by Django 3.0.3 on 2021-09-17 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileobject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
