# Generated by Django 3.0.3 on 2020-04-11 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tool', '0006_delete_usertool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('leader_user_id', models.IntegerField()),
                ('main_image', models.ImageField(default='defo', upload_to='work_main_image/')),
                ('intro', markdownx.models.MarkdownxField(verbose_name='intro')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Tool')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
