# Generated by Django 3.0.3 on 2020-03-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20200323_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_icon',
            field=models.ImageField(default='defo', upload_to='tool_icon/'),
        ),
    ]
