# Generated by Django 3.0.3 on 2020-04-04 08:22
from django.core.management import call_command
from django.db import migrations

#
# 無効化済み
#


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]
operations = [
        
    ]
    
