# Generated by Django 3.0.3 on 2020-04-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_delete_usertool'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Profile')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Tool')),
            ],
        ),
    ]
