# Generated by Django 3.0.3 on 2020-05-20 15:31

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20200503_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='intro'),
        ),
    ]
