# Generated by Django 3.0.3 on 2021-06-22 14:12

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20200521_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='自己紹介'),
        ),
    ]
