# Generated by Django 3.0.3 on 2020-04-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_delete_usertool'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='user',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='work',
            name='tool',
        ),
        migrations.AddField(
            model_name='work',
            name='tools',
            field=models.ManyToManyField(to='tool.Tool'),
        ),
    ]
