# Generated by Django 3.0.3 on 2020-04-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20200411_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('planning', 'planning'), ('making', 'making'), ('finished', 'finished')], default=0, max_length=10),
        ),
    ]
