# Generated by Django 3.0.3 on 2020-05-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='leader_user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
