# Generated by Django 3.0.3 on 2020-05-20 15:31

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20200504_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='intro',
            field=mdeditor.fields.MDTextField(verbose_name='intro'),
        ),
    ]
