# Generated by Django 3.0.3 on 2021-09-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_workitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='work.WorkTag'),
        ),
    ]
