# Generated by Django 3.0.3 on 2020-04-28 06:54

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_work_status'),
        ('blog', '0002_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletag',
            name='content',
            field=markdownx.models.MarkdownxField(default='', verbose_name='Contents'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_tags',
            field=models.ManyToManyField(blank=True, to='blog.ArticleTag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='relates_works',
            field=models.ManyToManyField(blank=True, to='work.Work'),
        ),
    ]
