# Generated by Django 3.0.3 on 2020-07-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogevent_eventarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventarticle',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
