# Generated by Django 3.0.3 on 2020-08-07 09:40

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200801_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogevent',
            name='content',
            field=mdeditor.fields.MDTextField(default='', verbose_name='Contents'),
        ),
    ]
