# Generated by Django 3.0.3 on 2020-11-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200813_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogevent',
            name='month',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='blogevent',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
