# Generated by Django 3.0.3 on 2020-05-20 15:31

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200428_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='Contents'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='Contents'),
        ),
    ]
