# Generated by Django 3.0.3 on 2020-08-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_eventarticle_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventarticle',
            options={'ordering': ('release_date',)},
        ),
    ]
