# Generated by Django 3.0.3 on 2020-08-13 11:20

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogevent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='Contents'),
        ),
    ]
