# Generated by Django 3.0.3 on 2020-12-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201114_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.URLField(default='null', verbose_name='サムネイル画像URL'),
        ),
    ]
