# Generated by Django 3.0.3 on 2021-08-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201206_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.URLField(blank=True, verbose_name='サムネイル画像URL'),
        ),
    ]
