# Generated by Django 3.0.5 on 2020-04-13 12:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ringi', '0001_initial'), ('ringi', '0002_auto_20200312_1813'), ('ringi', '0004_auto_20200328_1913'), ('ringi', '0005_auto_20200328_1949'), ('ringi', '0006_auto_20200401_1024'), ('ringi', '0007_auto_20200401_1538'), ('ringi', '0008_auto_20200401_1903'), ('ringi', '0009_auto_20200401_1909'), ('ringi', '0010_auto_20200404_1809'), ('ringi', '0011_auto_20200406_2123'), ('ringi', '0012_auto_20200409_0940'), ('ringi', '0013_auto_20200409_1502'), ('ringi', '0014_ringi_receipt_image')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_type', models.CharField(max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('color', models.CharField(default='', max_length=20)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency_type', models.CharField(default='', help_text='通常: 1週間待つ、幹部通さないで稟議→反応→会計最終判断, 緊急: 1週間待てない、幹部１人の確認しました, 事後報告: 超緊急、当日中、プリンターインクなど', max_length=10)),
                ('color', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ringi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='表題')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringi.Status', verbose_name='ステータス')),
                ('note', models.TextField(blank=True, default='', max_length=200, verbose_name='備考')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('purpose', models.CharField(default='', max_length=50, verbose_name='目的')),
                ('urgency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ringi.Urgency', verbose_name='緊急度')),
                ('is_pay_offed', models.BooleanField(default=False, verbose_name='精算済')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='購入済')),
                ('receipt_image', models.ImageField(default='defo', upload_to='receipt_image/')),
            ],
            options={
                'ordering': ('-urgency', '-created_at'),
            },
        ),
    ]
