# Generated by Django 2.2.5 on 2020-03-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ringi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ringi',
            old_name='name',
            new_name='title',
        ),
    ]
