# Generated by Django 3.0.3 on 2020-03-23 10:59

from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'ringi/fixture/init.json', app_label='ringi')

class Migration(migrations.Migration):

    dependencies = [
        ('ringi', '0002_auto_20200312_1813'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
