# Generated by Django 3.0.3 on 2020-03-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringi', '0002_auto_20200312_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='ringi',
            name='note',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ringi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='status',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
