# Generated by Django 3.0.3 on 2020-04-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringi', '0005_auto_20200328_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringi',
            name='note',
            field=models.TextField(default='', max_length=200),
        ),
    ]
