# Generated by Django 3.0.3 on 2020-04-01 06:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ringi', '0006_auto_20200401_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ringi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='ringi',
            name='note',
            field=models.TextField(default='', max_length=200, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='ringi',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
        migrations.AlterField(
            model_name='ringi',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='ringi',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringi.Status', verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='ringi',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='ringi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
