# Generated by Django 3.0.3 on 2020-04-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringi', '0007_auto_20200401_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='ringi',
            name='purpose',
            field=models.CharField(default='', max_length=50, verbose_name='目的'),
        ),
        migrations.AlterField(
            model_name='ringi',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
    ]
