# Generated by Django 3.0.3 on 2020-04-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringi', '0008_auto_20200401_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringi',
            name='note',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='備考'),
        ),
    ]
