# Generated by Django 3.0.3 on 2020-04-06 12:23

from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command

def load_fixture_urgency(apps, schema_editor):
    call_command('loaddata', 'ringi/fixture/init_urgency.json', app_label='ringi')

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'ringi/fixture/init.json', app_label='ringi')

class Migration(migrations.Migration):

    dependencies = [
        ('ringi', '0010_auto_20200404_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency_type', models.CharField(default='', help_text='通常: 1週間待つ、幹部通さないで稟議→反応→会計最終判断, 緊急: 1週間待てない、幹部１人の確認しました, 事後報告: 超緊急、当日中、プリンターインクなど', max_length=10)),
                ('color', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RunPython(load_fixture_urgency),
        migrations.AddField(
            model_name='ringi',
            name='urgency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ringi.Urgency', verbose_name='緊急度'),
            preserve_default=False,
        ),
        migrations.RunPython(load_fixture),
    ]
