# Generated by Django 3.0.3 on 2020-04-09 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringi', '0011_auto_20200406_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ringi',
            options={'ordering': ('-urgency', '-created_at')},
        ),
        migrations.AddField(
            model_name='ringi',
            name='is_pay_offed',
            field=models.BooleanField(default=False, verbose_name='精算済'),
        ),
        migrations.AddField(
            model_name='ringi',
            name='is_purchased',
            field=models.BooleanField(default=False, verbose_name='購入済'),
        ),
        migrations.AlterField(
            model_name='ringi',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='金額'),
        ),
    ]
