# Generated by Django 3.0.3 on 2020-04-09 06:02

from django.db import migrations, models
from django.core.management import call_command

def load_fixture_urgency(apps, schema_editor):
    call_command('loaddata', 'ringi/fixture/init_urgency.json', app_label='ringi')

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'ringi/fixture/init.json', app_label='ringi')

class Migration(migrations.Migration):

    dependencies = [
        ('ringi', '0012_auto_20200409_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringi',
            name='title',
            field=models.CharField(max_length=50, verbose_name='表題'),
        ),
        migrations.RunPython(load_fixture_urgency),
        migrations.RunPython(load_fixture),
    ]
