# Generated by Django 3.0.3 on 2020-04-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringi', '0012_auto_20200409_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringi',
            name='title',
            field=models.CharField(max_length=50, verbose_name='表題'),
        ),
    ]
