# Generated by Django 3.0.5 on 2020-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringi', '0013_auto_20200409_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='ringi',
            name='receipt_image',
            field=models.ImageField(default='defo', upload_to='receipt_image/'),
        ),
    ]
