# Generated by Django 3.0.5 on 2020-04-13 10:19

from django.db import migrations, models
from django.core.management import call_command

def load_fixture_urgency(apps, schema_editor):
    call_command('loaddata', 'ringi/fixture/init_urgency.json', app_label='ringi')

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'ringi/fixture/init.json', app_label='ringi')

class Migration(migrations.Migration):

    dependencies = [
        ('ringi', '0014_ringi_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringi',
            name='receipt_image',
            field=models.ImageField(default='defo', upload_to='receipt_image/', verbose_name='領収書'),
        ),
        migrations.RunPython(load_fixture_urgency),
        migrations.RunPython(load_fixture),
    ]
