# Generated by Django 3.0.3 on 2020-04-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_auto_20200323_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTool',
        ),
    ]
