# Generated by Django 3.0.3 on 2020-05-20 15:31

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_delete_usertool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='intro',
            field=mdeditor.fields.MDTextField(verbose_name='intro'),
        ),
    ]
