# Generated by Django 3.0.3 on 2020-05-19 14:43

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20200428_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='Contents'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='Contents'),
        ),
    ]
