name: CD

on:
  push:
    branches:
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: execute deploy ssh commands 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/groupware
          git checkout release
          git pull origin release
          docker-compose build
          docker-compose -f docker-compose.production.yml down
          docker-compose -f docker-compose.production.yml up -d
